---

- name: Execute MDATP enrollment
  ansible.builtin.command: /usr/bin/python3 potos_mdatp/MicrosoftDefenderATPOnboardingLinuxServer.py

- name: Set tag for mdatp
  command: /usr/bin/mdatp edr tag set --name GROUP --value {{ mdatp_tag | default('Workgroup') }}
  register: result
  failed_when: result.rc != 0 and result.rc != 2
  changed_when: result.rc != 2

- name: Reload mdatp systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  notify: restart mdatp

- name: Enable real-time-protection for mdatp
  command: /usr/bin/mdatp config real-time-protection --value {{ mdatp_realtime_protection | default('enabled') }}
  register: result
  failed_when: result.rc != 0 and result.rc != 2
  changed_when: result.rc != 2
